### PR TITLE
Use Vega-Lite for all analytics

### PR DESCRIPTION
**Pull request by michaelherger**
This still needs some tweaking, of course.

* connected players has a useless `undefined` label - but I don't have historical data for the player types
* the pie charts seem to be alphabetically ordered, rather than by slice size
* architecture IMHO doesn't make sense without the OS
* plugins... Hmm... not sure what to think about it. This might be interesting for plugin developers, but not so much for most user. As I added the installation numbers to the Plugins page, I believe this chart isn't useful.

### CODE REVIEW

**Comment by michaelherger** [comment]
@terual - thoughts? Ideas?

**Comment by terual** [comment]
Overall, looks very nice so far! 

> This still needs some tweaking, of course.
> * connected players has a useless `undefined` label - but I don't have historical data for the player types

We can do two things I think: start collecting historical data about players, or delete the `"color": {"field": "c", "type": "nominal", "title": "Total"},` line so we don't see the legend anymore.
 
> * the pie charts seem to be alphabetically ordered, rather than by slice size

I have tried everything to fix that, in the end only solved the ordering of the pie slices but not the legend... I gave up for now. Maybe it just need some more tweaking.
 
> * architecture IMHO doesn't make sense without the OS

I agree, I was thinking about plugin developers and bundled binaries, but that is of course also OS-dependent :see_no_evil: 
 
>     * plugins... Hmm... not sure what to think about it. This might be interesting for plugin developers, but not so much for most user. As I added the installation numbers to the Plugins page, I believe this chart isn't useful.

I was thinking of putting that chart on its own page (and maybe also just display it in a table).

Furthermore, it also seems we need to increase the size of the pie charts as the legend doesn't fit anymore. And I'm not sure about the "All" line in the number of LMS installations chart. It doesn't sit right we me that the sum of all other lines is a line as well.

**Comment by terual** [comment]
An idea to solve the total line in the version plot: we can move the total installs line to the connected players plot. Then we have two lines (total installations and total numbers of connected players). I think that makes more sense to me.

**Comment by terual** [comment]
Another issue: now that we plot the countries on a map we can remove the "Others" category.

**Comment by michaelherger** [comment]
Thanks a lot! Let's merge this and tweak as needed.

**Comment by terual** [comment]
I think we're sort of done? Any more charts on your wishlist? Maybe a pie chart with selected skin? Perl version? Number of tracks histogram (binned per 1000 of tracks)?

**Comment by terual** [comment]
Agree! :+1:

**Pull request merged**
