### PR TITLE
Update CLI documentation to add CometD/JSON examples

### PR DESCRIPTION
**Pull request by sodface**
Update CLI documentation to add CometD/JSON examples

### CODE REVIEW

**Comment by sodface** [comment]
Closes https://github.com/LMS-Community/lms-community.github.io/issues/74

**Comment by michaelherger** [comment]
Now that I read your documentation changes I'm wondering whether this all makes sense... I thought sending a request in JSON format over telnet would be all you'd need to use this. But you actually have to set up channels and what not in order to get JSON data? 

I tried to use the steps to send handshake etc. according to this PR. But I never got anything back as documented. Are the "Request" items exactly what you'd send over the CLI?

**Comment by michaelherger** [comment]
Thanks!

**Comment by sodface** [comment]
> Now that I read your documentation changes I'm wondering whether this all makes sense... I thought sending a request in JSON format over telnet would be all you'd need to use this. But you actually have to set up channels and what not in order to get JSON data?

Yes, I probably should have listened to you from the start and just used HTTP :)

Before my PRs,  CLI <-> CometD was really broken, now it might be somewhere between working and broken, depending on what the user tries to do, which might be a worse position to be in going forward as far as user support goes.

I can't fully tell if the original code was trying to support all CometD functionality or not, but it definitely still expected a clientID for the session and you couldn't just make up an arbitrary clientId since the existing code checked to see if was valid. That meant you had to do a /slim/handshake to get a clid assigned by the server.

I hope I didn't open a can of worms with this.

**Comment by sodface** [comment]
Just tested `/slim/subscribe` and that seems to be working now too (it didn't before) so that's a bonus!

```
[
	{
		"id": "1",
		"clientId": "970b6845",
		"channel": "/slim/subscribe",
		"data": {
			"response": "/slim/970b6845/subscribe",
			"request": [
				"",
				[
					"newmetadata"
				]
			]
		}
	}
]
```

**Pull request merged**
