### PR TITLE
Add links to source for Radio and Touch

### PR DESCRIPTION
**Pull request by PaulWebster**
Add links to source for Radio and Touch
Plus some tidy up including indication if payment required

### CODE REVIEW

**Comment by terual** [comment]
Thanks!!

**Comment by danielvijge** [comment]
Not sure if I should ask here, but what is the difference between [squeezeos](https://github.com/ralph-irving/squeezeos)/[squeezeplay](https://github.com/ralph-irving/squeezeplay) and [squeezeos-squeezeplay](https://github.com/ralph-irving/squeezeos-squeezeplay)?
There is still an open merge request from my side to the later repository, but maybe that should be submitted to the former?

**Comment by terual** [comment]
I'm not sure, @ralph-irving can you chime in?

**Comment by ralph-irving** [comment]
The source code for the community firmware is split into two repositories.
https://github.com/ralph-irving/squeezeos
and
https://github.com/ralph-irving/squeezeos-squeezeplay

The squeezeplay repository https://github.com/ralph-irving/squeezeplay is the source for the macos, windows and linux builds not for the firmware.

**Comment by terual** [comment]
Thanks, I have fixed the link to squeezeplay for the community firmware in [4a1e41d](https://github.com/LMS-Community/lms-community.github.io/commit/4a1e41d855df621575dd7c42f59cc565d692c2e2).

**Pull request merged**
