### PR TITLE
Update transporter.md

### PR DESCRIPTION
**Pull request by erwinberlin**
added hyperlinks
added link to owners manual on logitech site

### CODE REVIEW

**Comment by michaelherger** [comment]
We should probably try to archive copies of these files…

**Comment by erwinberlin** [comment]
Yup, totally agree, so I already downloaded all manuals, and Joe's tech blog a long time ago for archiving, just in case. 
 
Now my questions is how to upload/store this info on github? Probably some folder structure would be helpful, however, I can't create that (I guess?).
 
Best regards,
 
Erwin

**Comment by michaelherger** [comment]
You could certainly add a new folder with those files. But git isn't great to manager larger files (though I'd think those files aren't really large). I have archive.lyrion.org and downloads.lyrion.org where we can store such files. The former already has some (though they're not linked to anywhere...).

**Comment by erwinberlin** [comment]
Ah well. I get a kind of 404 experience here, which is most likely due to my limited experience with github. When I try to upload a file, I get a uploads disabled message.
 
Anyways, Is it possible to have an upload folder for manuals, and for images, or something like that?
 
I have lots of good intentions for 2025! All the best, and enjoy tonight. And we will talk in the new year.
 
Erwin

**Comment by terual** [comment]
> You could certainly add a new folder with those files. But git isn't great to manager larger files (though I'd think those files aren't really large). I have archive.lyrion.org and downloads.lyrion.org where we can store such files. The former already has some (though they're not linked to anywhere...).

Is one of those sites manageable by the community? If not, maybe it is then better to just store it here on GitHub. We could add a folder just for all these extra docs.

**Comment by michaelherger** [comment]
> Is one of those sites manageable by the community? If not, maybe it is then better to just store it here on GitHub. We could add a folder just for all these extra docs.

In theory: yes. In practice? I'm still looking for volunteers supporting me with "devops" work. See https://forums.slimdevices.com/forum/user-forums/general-discussion/1742335#post1742504. The download site is based on Cloudflare's R2 service (an AWS S3 compatible storage service).

**Comment by michaelherger** [comment]
> Ah well. I get a kind of 404 experience here, which is most likely due to my limited experience with github. When I try to upload a file, I get an uploads disabled message. Anyways, Is it possible to have an upload folder for manuals, and for images, or something like that?

Oh, you haven't cloned this repository to your computer? You're creating the pull requests on GitHub.com directly? I wouldn't know how to add a folder this way indeed. But if you have great plans for the new year (thanks a lot already!), it would probably be great if you learned how to work with a git clone. See eg. https://www.freecodecamp.org/news/how-to-fork-a-github-repository/ for a tutorial. With a local clone you would add a new folder with the files, then commit those files (not the folder!). The folder would be created as part of the file path.

**Comment by michaelherger** [comment]
Feel free to send me copies of those files to https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a.

**Comment by michaelherger** [comment]
Oh, there actually already are a few archived documents:

https://downloads.lms-community.org/docs/SLIMP3.pdf
https://downloads.lms-community.org/docs/squeezebox.pdf
https://downloads.lms-community.org/docs/CU40025SCPB-U1J.pdf

😁

**Comment by terual** [comment]
> > Is one of those sites manageable by the community? If not, maybe it is then better to just store it here on GitHub. We could add a folder just for all these extra docs.
> 
> In theory: yes. In practice? I'm still looking for volunteers supporting me with "devops" work. See https://forums.slimdevices.com/forum/user-forums/general-discussion/1742335#post1742504. The download site is based on Cloudflare's R2 service (an AWS S3 compatible storage service).

I would love to help, but in practice I do not have a lot of time for it (for lyrion.org you are almost always faster to react to pull requests :))

**Comment by erwinberlin** [comment]
Hi,
 
I uploaded some files, then checked and noticed that the file Portfolio Logitech.pdf is corrupt. So, better delete that one without opening!
 
Apologies for the inconvenience.

Erwin

**Comment by michaelherger** [comment]
Thanks guys. I'll look into adding them soon.

**Comment by terual** [comment]
Nice, thank you for also adding all the text!

**Comment by erwinberlin** [comment]
Hi,
 
many thanks for adding the links!
 
In the meantime, I have contacted Johannes Franke from Joes's tech blog, and he is interested in moving his repair guides to the Lyrion site.
 
Is it possible to add a repair section to the site? Or how much freedom does a contributor have in adding/changing the site?
 
Best regards,
 
Erwin

**Comment by michaelherger** [comment]
Great! I was considering adding that page, too. To have it archived in case his went away.

I don't know whether we need a dedicated "Repair" section. Just linking from the Transporter page should be good enough, as long as we don't have dozens of repair pages.

**Pull request merged**
