### PR TITLE
Add Python module (py file) and Python code examples page to docs/ref…

### PR DESCRIPTION
**Pull request by Daksol**
This adds:-
* a (small) Python module, essentially with just one function.
* a documentation page with Python code examples of CLI via JSON/RPC

Reason for doing this:
* Useful for anyone wanting to work with the CLI, or documenting the CLI
* The JSON/RPC provides much more readable data than does the Telnet
* Doing this with Python easily gives a readable and accessible way of working with JSON/RPC 

 On branch CLI-Python
 Your branch is up to date with 'origin/CLI-Python'.

 Changes to be committed:
	new file:   reference/cli/lms_jsonrpc_module.py
	new file:   reference/cli/python-cli.md
	modified:   reference/cli/using-the-cli.md
	modified:   ../mkdocs.yml

### CODE REVIEW

**Comment by michaelherger** [comment]
I'd prefer if you created a repo for your example code and linked there from lyrion.org. This could be the starting point for a series of links to projects related to LMS in many languages?

What do you think?

**Comment by Daksol** [comment]
MichaeL
Understood. I wil establish repository as you suggest. I am posting a couple of questions for you about that in the CLI thread in the Documentation Project. 

Leaving this request open, - once repo in place I will update it.

**Comment by Daksol** [comment]
Changes as discussed:
* CLI documentation page generalised to "language support"
* Python module now part of external github repository, linked ex documentation page

**Comment by michaelherger** [comment]
I'm sorry, I think there's been a misunderstanding: I didn't want to ask to have a new repo to collect all those little tools. I rather thought all those integrations would have their own repo already anyway (eg. https://github.com/molobrakos/lms, https://github.com/GeoffAtHome/squeezenode). Why not add a page which simply points there? The documentation for those tools should be maintained by their creators, not Lyrion.

**Comment by Daksol** [comment]
Understood. Not previously aware of either molobrakos/lms or GeoffAtHome/squeezenode.

I will look at best way of linking to those. I will delete existing pull request.

I did do fairly detailed trawls for LMS Python related material, finding nearly 20 repos and modules, but I did not notice those.

**Pull request closed without merging**
