### PR TITLE
add note for Raspberry Pi OS

### PR DESCRIPTION
**Pull request by vincss**
Following : https://forums.slimdevices.com/forum/user-forums/3rd-party-software/110192-announce-community-firmware-for-squeezebox-radio-touch-controller-and-lms-8?p=1669416#post1669416

### CODE REVIEW

**Review by michaelherger — CHANGES_REQUESTED** [review]
I think that this comment is in a confusing place: the section below would recommend pCP - which I would personally recommend for beginners too. And that would "just work". 

Maybe the section could be split in beginners and advanced. The latter then would explain how to install on RPiOS.

**Comment by vincss** [comment]
Hi,
Yes I agree it can be confusing, from my latest experience, I would recommend using Raspberry Pi OS instead of Ubuntu for LMS usage.

**Comment by terual** [comment]
I think what Michael means is that we want to advise using pCP instead of Raspberry Pi OS or Ubuntu for beginners. That is the only real easy way to get a LMS install up-and-running on a Raspberry. If you want to go the Raspberry Pi OS route you are required to have some linux/networking skills.

**Comment by vincss** [comment]
Yes, I understood the confusing point.

**Comment by terual** [comment]
I thought about it some more. I don't think it would be beneficial to include this warning. Please report any issues you have with installing LMS on Debian/Ubuntu to [Logitech/slimserver](https://github.com/Logitech/slimserver), instead of working around this issue in documentation.

**Pull request closed without merging**
