### PR TITLE
add iobroker/squeezeboxrpc plugin as an integration into smart home s…

### PR DESCRIPTION
**Pull request by oweitman**
…ystem

### CODE REVIEW

**Review by michaelherger — COMMENTED** [review]
Thanks for this addition! I'm still hesitating to add another section... We'd have to cover others as well. But wouldn't a link to the corresponding pages of the projects be good enough? Otherwise we risk to look dated shortly. The projects will update their pages, but not ours.

**Comment by oweitman** [comment]
Thanks for this addition! I'm still hesitating to add another section... We'd have to cover others as well. But wouldn't a link to the corresponding pages of the projects be good enough? Otherwise we risk to look dated shortly. The projects will update their pages, but not ours.

**Comment by michaelherger** [comment]
Heh... I didn't realise you were the extension's author! While I don't doubt the longevity of the project, my concern is more that the extension would get potential updates, but we'd stay behind with the description. That's probably less of a problem if you took ownership of this document here, and updated it in addition to your project's pages. But with other projects this might not be the case. Therefore I usually prefer to link to the "original" pages, rather than have a copy of them.

**Comment by oweitman** [comment]
> if you took ownership of this document here, and updated it in addition to your project's pages. 

Yes i will

> Therefore I usually prefer to link to the "original" pages, rather than have a copy of them.

this point i dont understand exactly, with this PR i only add an overview with some screenshots. the link to the github repository with the detailed description is also included

**Comment by michaelherger** [comment]
My point is: you're still duplicating information and screenshots. While you'll update the main page, you won't go to all the pages where you've introduced these duplications to keep those up to date as well. This page will become stale and dated, while your main project page evolves. Therefore I'd suggest you have a single source of truth: your page. Everybody else should simply link to yours.

**Comment by oweitman** [comment]
Now the amount of discussion exceeds the value of the information. I will now withdraw the PR

**Pull request closed without merging**
